const $=id=>document.getElementById(id);
const products=[
{id:'nike-vapor17-academy',brand:'Nike',name:'Mercurial Vapor 17 Academy',level:'Academy',surface:['ag','mg','tf','sala'],profile:['speed'],fit:['snug','natural'],closure:'laces',price:89.99,checked:'27/09/2026',source:'https://www.nike.com/es/w/academy-3abn9z90poyz9w87t',desc:'Bota de perfil bajo de la familia Mercurial, orientada a velocidad. La variante cambia según la superficie, así que comprueba la suela exacta antes de comprar.',features:['Gama Academy','Familia orientada a velocidad','Disponible en variantes para distintas superficies'],tag:'Velocidad'},
{id:'nike-vapor17-pro',brand:'Nike',name:'Mercurial Vapor 17 Pro',level:'Pro',surface:['ag','fg'],profile:['speed'],fit:['snug','natural'],closure:'laces',price:159.99,checked:'27/09/2026',source:'https://www.nike.com/es/mercurial/vapor',desc:'Modelo Pro de Mercurial Vapor 17. Nike presenta la familia Mercurial como su línea orientada a velocidad y ofrece variantes para distintas superficies.',features:['Gama Pro','Orientada a velocidad','Variantes AG y FG'],tag:'Velocidad'},
{id:'nike-phantom6-low-academy',brand:'Nike',name:'Phantom 6 Low Academy',level:'Academy',surface:['ag','mg','sala'],profile:['control'],fit:['natural'],closure:'laces',price:89.99,checked:'27/09/2026',source:'https://www.nike.com/es/w/academy-3abn9z90poyz9w87t',desc:'Modelo Academy de Phantom 6 Low. Nike sitúa Phantom en su propuesta de precisión y control.',features:['Gama Academy','Familia Phantom orientada a precisión','Variantes según superficie'],tag:'Precisión'},
{id:'nike-phantom6-low-pro',brand:'Nike',name:'Phantom 6 Low Pro',level:'Pro',surface:['ag','fg','tf'],profile:['control'],fit:['natural'],closure:'laces',price:159.99,checked:'27/09/2026',source:'https://www.nike.com/es/w/pro-zapatillas-1gdj0z2a2jz90dwjzy7ok',desc:'Modelo Pro de Phantom 6 Low. La variante AG está diseñada para césped artificial y Nike la presenta dentro de su línea de precisión.',features:['Gama Pro','Variante AG para césped artificial','Nike la posiciona en precisión'],tag:'Precisión'},
{id:'nike-tiempo-react-gato',brand:'Nike',name:'Tiempo React Gato',level:'Pro',surface:['sala'],profile:['control','allround'],fit:['natural'],closure:'laces',price:119.99,checked:'27/09/2026',source:'https://www.nike.com/es/w/pro-zapatillas-1gdj0z2a2jz90dwjzy7ok',desc:'Bota de fútbol sala de perfil bajo de la familia Tiempo React Gato.',features:['Fútbol sala','Perfil bajo','Familia Tiempo orientada al toque'],tag:'Toque'},
{id:'adidas-f50-league-fg-mg',brand:'adidas',name:'F50 League FG/MG',level:'League',surface:['fg','mg'],profile:['speed'],fit:['standard'],closure:'laces',price:79.99,checked:'27/09/2026',source:'https://www.adidas.es/f50',desc:'F50 League con suela FG/MG. adidas sitúa F50 dentro de su propuesta de velocidad.',features:['FG/MG','Horma clásica','Cierre de cordones'],tag:'Velocidad'},
{id:'adidas-f50-league-ag',brand:'adidas',name:'F50 League AG',level:'League',surface:['ag'],profile:['speed'],fit:['standard'],closure:'laces',price:79.99,checked:'27/09/2026',source:'https://www.adidas.es/f50',desc:'Variante F50 League específica para césped artificial.',features:['AG','Horma clásica','Cierre de cordones'],tag:'Velocidad'},
{id:'adidas-predator-league-ag',brand:'adidas',name:'Predator League AG',level:'League',surface:['ag'],profile:['control','power'],fit:['standard'],closure:'laces',price:89.99,checked:'27/09/2026',source:'https://www.adidas.es/predator',desc:'Predator League con suela para césped artificial. adidas destaca elementos de control y contacto con el balón en la familia Predator.',features:['AG','Horma clásica','Cierre de cordones','Tecnología Nanostrike+'],tag:'Control'},
{id:'adidas-copa-pure3-league',brand:'adidas',name:'Copa Pure 3 League',level:'League',surface:['ag','fg','mg'],profile:['control','allround'],fit:['standard'],closure:'laces',price:79.99,checked:'27/09/2026',source:'https://www.adidas.es/copa',desc:'Copa Pure 3 League con variantes multisuperficie. La familia Copa se orienta al toque y comodidad.',features:['Multisuperficie','Horma clásica','Cierre de cordones'],tag:'Toque'},
{id:'puma-ultra6-match',brand:'PUMA',name:'ULTRA 6 Match FG/AG',level:'Match',surface:['fg','ag'],profile:['speed'],fit:['snug'],closure:'laces',price:84.99,checked:'27/09/2026',source:'https://eu.puma.com/es/es/c/futbol',desc:'ULTRA 6 Match FG/AG. PUMA la posiciona alrededor de velocidad y aceleración; su ajuste se describe como estándar a estrecho.',features:['FG/AG','Ajuste estándar a estrecho','Cordones','Orientada a velocidad'],tag:'Velocidad'},
{id:'puma-future9-match',brand:'PUMA',name:'FUTURE 9 Match FG/AG',level:'Match',surface:['fg','ag'],profile:['control','allround'],fit:['standard'],closure:'laces',price:94.99,checked:'27/09/2026',source:'https://eu.puma.com/es/es/c/futbol',desc:'FUTURE 9 Match FG/AG con zonas de relieve en el empeine para favorecer un contacto seguro y suela para terreno firme y césped artificial.',features:['FG/AG','Relieve para control','Terreno firme y artificial'],tag:'Control'},
{id:'puma-future9-pro',brand:'PUMA',name:'FUTURE 9 Pro FG/AG',level:'Pro',surface:['fg','ag'],profile:['control','allround'],fit:['standard'],closure:'laces',price:149.99,checked:'27/09/2026',source:'https://eu.puma.com/es/es/c/futbol',desc:'Versión Pro de la familia FUTURE 9 para FG/AG. La gama FUTURE se centra en libertad de movimiento y control.',features:['FG/AG','Gama Pro','Familia FUTURE'],tag:'Control'}
];
const surfaceNames={ag:'Césped artificial · AG',fg:'Césped natural firme · FG',mg:'Multiterreno · MG',tf:'Turf · TF',sala:'Fútbol sala'};
const profileNames={speed:'Velocidad',control:'Precisión / control',power:'Potencia',allround:'Equilibrio'};
const fitNames={snug:'Ceñido',standard:'Estándar',natural:'Natural',any:'Sin preferencia'};
function criteria(x,s,p,f,b,c){return [['Superficie',x.surface.includes(s)],['Estilo',x.profile.includes(p)],['Ajuste',f==='any'||x.fit.includes(f)],['Presupuesto',x.price<=b],['Cierre',c==='either'||x.closure===c]]}
function resultCard(x,q){return `<article class="result"><div class="result-top"><div><span class="brand-pill">${x.brand}</span><h3>${x.name}</h3><small>${x.level} · ${x.tag}</small></div><span class="match">${q.filter(a=>a[1]).length}/5</span></div><div class="chips">${q.map(a=>`<span class="${a[1]?'yes':''}">${a[1]?'✓':'×'} ${a[0]}</span>`).join('')}</div><div class="result-bottom"><strong>${x.price.toFixed(2).replace('.',',')} €</strong><a class="text-btn" href="botas/${x.id}.html">Ver ficha →</a></div></article>`}
function search(){const s=$('surface').value,p=$('profile').value,f=$('fit').value,b=+$('budget').value,c=$('closure').value;const r=products.map(x=>({x,q:criteria(x,s,p,f,b,c)})).map(o=>({...o,score:o.q.filter(a=>a[1]).length})).sort((a,b)=>b.score-a.score||a.x.price-b.x.price);$('results').innerHTML=`<div class="results-head"><b>${r.filter(x=>x.score>=3).length} coincidencias relevantes</b><span>Ordenadas por criterios coincidentes</span></div>${r.slice(0,6).map(o=>resultCard(o.x,o.q)).join('')}`;bindDynamic();}
function productDetail(id){const x=products.find(p=>p.id===id);$('modalContent').innerHTML=`<span class="brand-pill">${x.brand} · ${x.level}</span><h2>${x.name}</h2><p class="modal-price">${x.price.toFixed(2).replace('.',',')} €</p><p class="muted">${x.desc}</p><div class="spec-grid"><div><b>Superficie</b><span>${x.surface.map(s=>surfaceNames[s].split(' · ')[1]||surfaceNames[s]).join(' · ')}</span></div><div><b>Perfil</b><span>${x.profile.map(p=>profileNames[p]).join(' · ')}</span></div><div><b>Ajuste</b><span>${x.fit.map(f=>fitNames[f]).join(' / ')}</span></div><div><b>Cierre</b><span>${x.closure==='laces'?'Cordones':'Sin cordones'}</span></div></div><h3>Características verificadas</h3><ul class="feature-list">${x.features.map(f=>`<li>✓ ${f}</li>`).join('')}</ul><p class="source-note">Precio observado: ${x.checked}. Puede cambiar según talla, color o promoción.</p><a class="btn" href="${x.source}" target="_blank" rel="noopener">Ver fuente oficial ↗</a>`;$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false');}
function fillCompare(){const opts=products.map(x=>`<option value="${x.id}">${x.brand} — ${x.name}</option>`).join('');$('compareA').innerHTML=opts;$('compareB').innerHTML=opts;$('compareA').selectedIndex=0;$('compareB').selectedIndex=3;renderCompare();}
function renderCompare(){const a=products.find(x=>x.id===$('compareA').value),b=products.find(x=>x.id===$('compareB').value);const rows=[['Superficie',a.surface.map(s=>surfaceNames[s].split(' · ')[1]||surfaceNames[s]).join(', '),b.surface.map(s=>surfaceNames[s].split(' · ')[1]||surfaceNames[s]).join(', ')],['Perfil',a.profile.map(p=>profileNames[p]).join(', '),b.profile.map(p=>profileNames[p]).join(', ')],['Ajuste',a.fit.map(f=>fitNames[f]).join(' / '),b.fit.map(f=>fitNames[f]).join(' / ')],['Cierre',a.closure==='laces'?'Cordones':'Sin cordones',b.closure==='laces'?'Cordones':'Sin cordones'],['Precio observado',a.price.toFixed(2).replace('.',',')+' €',b.price.toFixed(2).replace('.',',')+' €'],['Nivel',a.level,b.level]];$('compareResult').innerHTML=`<div class="compare-head"><div><span class="brand-pill">${a.brand}</span><h3>${a.name}</h3></div><strong>VS</strong><div><span class="brand-pill">${b.brand}</span><h3>${b.name}</h3></div></div><div class="table">${rows.map(r=>`<div class="tr"><span>${r[0]}</span><b>${r[1]}</b><b>${r[2]}</b></div>`).join('')}</div><p class="comparison-note">La comparación describe diferencias documentadas del catálogo. No asignamos una puntuación global ni declaramos un modelo como «mejor».</p>`}
const guides=[['Cómo elegir botas de fútbol','Empieza por la superficie: una suela AG, FG, MG o TF no es intercambiable por defecto. Después piensa en tu estilo de juego, el ajuste que buscas y el presupuesto. Finalmente, comprueba la variante exacta del modelo y su talla.'],['AG vs FG vs MG vs TF','AG significa Artificial Ground y está pensado para césped artificial. FG se utiliza principalmente en césped natural firme. MG indica una configuración multi-ground y TF utiliza tacos pequeños para turf/moqueta. La nomenclatura puede variar entre marcas, por lo que conviene revisar la ficha del fabricante.'],['Cómo saber si una bota te queda bien','La longitud no debería dejar el pie bailando ni comprimir los dedos. El talón debe quedar sujeto y el contacto con el empeine debe sentirse estable sin puntos de presión. Si dudas entre dos tallas, consulta la guía específica de la marca y prueba la bota con los calcetines que utilizas para jugar.'],['Cómo cuidar tus botas','Retira barro y suciedad después de jugar, deja que se sequen de forma natural y evita fuentes de calor directo. No las guardes húmedas dentro de una bolsa cerrada. Utiliza el método de limpieza recomendado por el fabricante para el material de la parte superior.']];
function guide(i){const g=guides[i];$('modalContent').innerHTML=`<span class="brand-pill">GUÍA 0${i+1}</span><h2>${g[0]}</h2><p class="modal-guide">${g[1]}</p><button class="btn" id="closeGuide">Entendido</button>`;$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false');$('closeGuide').onclick=closeModal;}
function bindDynamic(){document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>productDetail(b.dataset.product));}
function closeModal(){$('modal').classList.remove('open');$('modal').setAttribute('aria-hidden','true')}
$('find').onclick=search;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const t=b.dataset.c;if(t==='speed'){let d=+$('sd').value,s=+$('st').value;$('sr').value=d>0&&s>0?(d/s*3.6).toFixed(2)+' km/h':'Introduce datos válidos'}if(t==='sprint'){let d=+$('srd').value,s=+$('srt').value,x=+$('target').value;$('srr').value=d>0&&s>0&&x>0?(s*x/d).toFixed(2)+' s (estimación lineal)':'Introduce datos válidos'}if(t==='convert'){let v=+$('cv').value,d=$('dir').value;$('cr').value=v>=0?(d==='a'?(v/3.6).toFixed(2)+' m/s':(v*3.6).toFixed(2)+' km/h'):'Introduce un valor válido'}});
if(localStorage.getItem('fm-theme')==='dark')document.body.classList.add('dark');$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('fm-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('fm-cookie')==='1')$('cookies').classList.add('hidden');$('accept').onclick=()=>{localStorage.setItem('fm-cookie','1');$('cookies').classList.add('hidden')};
$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>guide(+b.dataset.guide));fillCompare();$('compareA').onchange=renderCompare;$('compareB').onchange=renderCompare;
